"""add exercise categories

Revision ID: dad633939ff3
Revises: 8545a05c8e26
Create Date: 2026-01-16 10:56:52.731611

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dad633939ff3'
down_revision: Union[str, Sequence[str], None] = '8545a05c8e26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercise_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('therapist_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['therapist_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('course_exercises', sa.Column('category_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'course_exercises', 'exercise_categories', ['category_id'], ['id'])
    op.alter_column('evaluation_criterion_scores', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('evaluation_criterion_scores', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.drop_index(op.f('ix_evaluation_criterion_scores_id'), table_name='evaluation_criterion_scores')
    op.alter_column('evaluations', 'is_locked',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('evaluations', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('evaluations', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('evaluations', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_index(op.f('ix_evaluations_id'), table_name='evaluations')
    op.alter_column('exercise_weightings', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('exercise_weightings', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.drop_index(op.f('ix_exercise_weightings_id'), table_name='exercise_weightings')
    op.drop_index(op.f('ix_profiles_id'), table_name='profiles')
    op.alter_column('rubric_criteria', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('rubric_criteria', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('rubric_criteria', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_index(op.f('ix_rubric_criteria_id'), table_name='rubric_criteria')
    op.alter_column('rubric_levels', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('rubric_levels', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_index(op.f('ix_rubric_levels_id'), table_name='rubric_levels')
    op.alter_column('rubric_templates', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('rubric_templates', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('rubric_templates', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_index(op.f('ix_rubric_templates_id'), table_name='rubric_templates')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_rubric_templates_id'), 'rubric_templates', ['id'], unique=False)
    op.alter_column('rubric_templates', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('rubric_templates', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('rubric_templates', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.create_index(op.f('ix_rubric_levels_id'), 'rubric_levels', ['id'], unique=False)
    op.alter_column('rubric_levels', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('rubric_levels', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.create_index(op.f('ix_rubric_criteria_id'), 'rubric_criteria', ['id'], unique=False)
    op.alter_column('rubric_criteria', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('rubric_criteria', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('rubric_criteria', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.create_index(op.f('ix_profiles_id'), 'profiles', ['id'], unique=False)
    op.create_index(op.f('ix_exercise_weightings_id'), 'exercise_weightings', ['id'], unique=False)
    op.alter_column('exercise_weightings', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('exercise_weightings', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.create_index(op.f('ix_evaluations_id'), 'evaluations', ['id'], unique=False)
    op.alter_column('evaluations', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('evaluations', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('evaluations', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('evaluations', 'is_locked',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.create_index(op.f('ix_evaluation_criterion_scores_id'), 'evaluation_criterion_scores', ['id'], unique=False)
    op.alter_column('evaluation_criterion_scores', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('evaluation_criterion_scores', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.drop_constraint(None, 'course_exercises', type_='foreignkey')
    op.drop_column('course_exercises', 'category_id')
    op.drop_table('exercise_categories')
    # ### end Alembic commands ###
